# -*- coding: utf-8 -*-
"""Named watchlist presets under ``config/watchlists/``.

Presets are plain text files: ``#`` comments, codes separated by commas/whitespace.
They feed ``STOCK_LIST`` (via apply script) and the prediction accuracy chain.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional

from src.services.stock_list_parser import serialize_stock_list, split_stock_list

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
WATCHLIST_DIR = REPO_ROOT / "config" / "watchlists"
DEFAULT_WATCHLIST_NAME = "ai_focus"


def watchlist_dir() -> Path:
    return WATCHLIST_DIR


def list_watchlists() -> List[str]:
    """Return preset names (file stems) sorted alphabetically."""
    if not WATCHLIST_DIR.is_dir():
        return []
    return sorted(path.stem for path in WATCHLIST_DIR.glob("*.txt") if path.is_file())


def resolve_watchlist_path(name: str) -> Path:
    raw = str(name or "").strip()
    if not raw:
        raise ValueError("watchlist name is required")
    # allow "ai_focus" or "ai_focus.txt"
    stem = raw[:-4] if raw.lower().endswith(".txt") else raw
    if "/" in stem or "\\" in stem or stem in {".", ".."}:
        raise ValueError(f"invalid watchlist name: {name}")
    path = WATCHLIST_DIR / f"{stem}.txt"
    if not path.is_file():
        available = ", ".join(list_watchlists()) or "(none)"
        raise FileNotFoundError(f"watchlist '{stem}' not found under {WATCHLIST_DIR}; available: {available}")
    return path


def load_watchlist_codes(name: str = DEFAULT_WATCHLIST_NAME) -> List[str]:
    """Load unique stock codes from a named preset file."""
    path = resolve_watchlist_path(name)
    codes: List[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        # allow inline trailing comments
        if "#" in stripped:
            stripped = stripped.split("#", 1)[0].strip()
        codes.extend(split_stock_list(stripped))
    return list(dict.fromkeys(codes))


def watchlist_as_stock_list(name: str = DEFAULT_WATCHLIST_NAME) -> str:
    """Return preset codes in canonical ``STOCK_LIST`` comma-separated form."""
    return serialize_stock_list(",".join(load_watchlist_codes(name)))


def describe_watchlists() -> Dict[str, Dict[str, object]]:
    """Return name -> {path, count, codes} for all presets."""
    result: Dict[str, Dict[str, object]] = {}
    for name in list_watchlists():
        codes = load_watchlist_codes(name)
        result[name] = {
            "name": name,
            "path": str(resolve_watchlist_path(name).relative_to(REPO_ROOT)),
            "count": len(codes),
            "codes": codes,
        }
    return result


def apply_watchlist_to_env_file(
    name: str = DEFAULT_WATCHLIST_NAME,
    *,
    env_path: Optional[Path] = None,
) -> Dict[str, object]:
    """Upsert ``STOCK_LIST`` in a ``.env`` file from the named preset.

    Does not print or log secret values from other keys.
    """
    target = env_path or (REPO_ROOT / ".env")
    stock_list = watchlist_as_stock_list(name)
    codes = split_stock_list(stock_list)
    if not codes:
        raise ValueError(f"watchlist '{name}' is empty")

    lines: List[str]
    if target.is_file():
        lines = target.read_text(encoding="utf-8").splitlines()
    else:
        lines = [
            "# Generated by scripts/apply_watchlist.py",
            "# Fill remaining secrets from .env.example",
        ]

    replaced = False
    new_lines: List[str] = []
    for line in lines:
        if line.strip().startswith("STOCK_LIST="):
            new_lines.append(f"STOCK_LIST={stock_list}")
            replaced = True
        else:
            new_lines.append(line)
    if not replaced:
        # insert after header comments if possible
        insert_at = 0
        for idx, line in enumerate(new_lines):
            if line.strip() and not line.strip().startswith("#"):
                insert_at = idx
                break
            insert_at = idx + 1
        new_lines.insert(insert_at, f"STOCK_LIST={stock_list}")

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
    try:
        target.chmod(0o600)
    except OSError:
        pass

    return {
        "watchlist": name,
        "env_path": str(target),
        "count": len(codes),
        "stock_list": stock_list,
        "replaced": replaced,
    }
